// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caksbtqeowmzlagbqjdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNha3NidHFlb3dtemxhZ2JxamRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjMyNDIsImV4cCI6MjA2NDUzOTI0Mn0.JU6t6xxscY7-5YWiJ-tIw0vAEAeY22hYVinOdJflM4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);