// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these values with your Supabase project credentials
// Get these from your Supabase project settings > API
const SUPABASE_URL = "your-supabase-url-here eg.https://gbqjdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "your-supabase-publishable-key-here eg.eyJhbGciOiJIUzI1NiIsInR5cCI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);